name: Provision Database

on:
  workflow_dispatch:
    inputs:
      run_seed:
        description: 'Run seed data'
        required: false
        default: 'true'
        type: boolean

jobs:
  provision:
    name: Provision Supabase Database
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Verify secrets
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "::error::DATABASE_URL secret is missing"; exit 1
          fi

      - name: Prepare DB URL (ensure sslmode=require)
        run: |
          if [[ "${{ secrets.DATABASE_URL }}" == *\?* ]]; then
            echo "DB_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          else
            echo "DB_URL=${{ secrets.DATABASE_URL }}?sslmode=require" >> $GITHUB_ENV
          fi

      - name: Apply 00_schema.sql
        run: psql "$DB_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/00_schema.sql

      - name: Apply 01_rls.sql
        run: psql "$DB_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/01_rls.sql

      - name: Apply 02_seed.sql
        if: ${{ github.event.inputs.run_seed == 'true' || github.event.inputs.run_seed == '' }}
        run: psql "$DB_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/02_seed.sql

      - name: Apply 03_storage.sql
        run: psql "$DB_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/03_storage.sql

      - name: Summary
        run: |
          echo "## Database Provisioning Complete! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "✅ Schema created" >> $GITHUB_STEP_SUMMARY
          echo "✅ RLS policies applied" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event.inputs.run_seed }}" != "false" ]; then
            echo "✅ Seed data loaded" >> $GITHUB_STEP_SUMMARY
          fi
          echo "✅ Storage configured" >> $GITHUB_STEP_SUMMARY
